replicaCount: 1
image:
  repository: # wird von CI/CD gesetzt
  tag: latest
  pullPolicy: Always

service:
  port: 8080

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: ALPACA_API_KEY
    valueFrom:
      secretKeyRef:
        name: alpaca-credentials
        key: api-key
  - name: ALPACA_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: alpaca-credentials
        key: secret-key
  - name: KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      secretKeyRef:
        name: kafka-credentials
        key: bootstrap-servers
  - name: SYMBOLS
    value: "AAPL,MSFT,GOOGL,AMZN,NVDA"
