replicaCount: 1
image:
  repository: 710220507619.dkr.ecr.us-east-1.amazonaws.com/trading-engine-dev-order-executor
  tag: latest
  pullPolicy: Always

service:
  port: 8080

resources:
  requests:
    cpu: 125m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  - name: ALPACA_API_KEY
    valueFrom:
      secretKeyRef:
        name: alpaca-credentials
        key: api-key
  - name: ALPACA_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: alpaca-credentials
        key: secret-key
  - name: KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      secretKeyRef:
        name: kafka-credentials
        key: bootstrap-servers
  - name: KAFKA_GROUP_ID
    value: "order-executor-group"
  - name: PAPER_TRADING
    value: "true"
  - name: ORDER_TYPE
    value: "market"
