replicaCount: 1
image:
  repository: # wird von CI/CD gesetzt
  tag: latest
  pullPolicy: Always

service:
  port: 8080

resources:
  requests:
    cpu: 125m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      secretKeyRef:
        name: kafka-credentials
        key: bootstrap-servers
  - name: KAFKA_GROUP_ID
    value: "signal-aggregator-group"
  - name: SIGNAL_TTL_SECONDS
    value: "60"
